name: CI/CD Pipeline

on:
  push:
    branches: 
      - master
      - develop
      - 'release/**'
    tags:
      - 'v*'
  pull_request:
    branches: 
      - master
      - develop
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

env:
  DOTNET_VERSION: '8.0.x'
  NODE_VERSION: '18'
  PNPM_VERSION: '8.12.0'

jobs:
  validate:
    name: Validate
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Validate Commit Message
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(feat|fix|docs|style|refactor|test|chore|ci)(\(.+\))?: .+$'
          error: 'Commit message must follow conventional commits format'
          checkAllCommitMessages: true
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    name: Build and Test
    needs: validate
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-


    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          src-tauri/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Cache Tauri dependencies
      uses: actions/cache@v3
      with:
        path: |
          C:\Users\runneradmin\.cache\tauri
          src-tauri\.cache
        key: ${{ runner.os }}-tauri-${{ hashFiles('src-tauri/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-tauri-

    - name: Install Frontend Dependencies
      run: pnpm install --frozen-lockfile
      working-directory: FinanceiroApp.FrontEnd

    - name: Build Frontend
      run: pnpm build
      working-directory: FinanceiroApp.FrontEnd

    - name: Test Frontend
      run: pnpm test -- --watch=false --browsers=ChromeHeadless
      working-directory: FinanceiroApp.FrontEnd

    - name: Restore Backend Dependencies
      run: dotnet restore
      
    - name: Build Backend
      run: dotnet publish Financeiro.API/Financeiro.API.csproj -c Release

    - name: Test Backend
      run: dotnet test --no-restore --verbosity normal

    - name: Install Tauri Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Tauri App
      if: github.event_name != 'pull_request'
      run: pnpm tauri build

    - name: Upload MSI Installer
      uses: actions/upload-artifact@v3
      if: github.event_name != 'pull_request'
      with:
        name: financeiro-app-msi
        path: src-tauri/target/release/bundle/msi/*.msi
        retention-days: 7

    - name: Upload NSIS Installer
      uses: actions/upload-artifact@v3
      if: github.event_name != 'pull_request'
      with:
        name: financeiro-app-setup
        path: src-tauri/target/release/bundle/nsis/*.exe
        retention-days: 7

  release:
    name: Create Release
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    
    steps:
      - name: Download MSI Artifact
        uses: actions/download-artifact@v3
        with:
          name: financeiro-app-msi
          path: msi

      - name: Download NSIS Artifact
        uses: actions/download-artifact@v3
        with:
          name: financeiro-app-setup
          path: setup

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            msi/*.msi
            setup/*.exe
          body: |
            ## FinanceiroApp Release ${{ github.ref_name }}
            
            ### Instaladores
            - 💿 MSI Installer (Recomendado para instalação silenciosa/empresarial)
            - 🚀 Setup EXE (Instalador tradicional com interface)
            
            ### Notas da Versão
            Para ver as mudanças completas, consulte o [CHANGELOG.md](./CHANGELOG.md)
            
            ### Instruções de Instalação
            1. Baixe o instalador de sua preferência (MSI ou EXE)
            2. Execute o instalador como administrador
            3. Siga as instruções na tela
            
            ### Requisitos do Sistema
            - Windows 10 ou superior (64-bit)
            - 4GB RAM (mínimo)
            - 500MB de espaço em disco
          draft: false
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}

  notify:
    name: Notify Status
    needs: [build-and-test]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
    - name: Report Status
      uses: actions/github-script@v6
      with:
        script: |
          const { conclusion } = context.payload;
          const status = conclusion === 'success' ? '✅' : '❌';
          const message = `${status} Pipeline ${conclusion}\n\nBranch: ${process.env.GITHUB_REF}\nCommit: ${process.env.GITHUB_SHA}\nDetails: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
          
          if (context.eventName === 'pull_request') {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
          }
